// GENERATED by scripts/sync_creatures.mjs from backend/src/data/creatures.json.
// DO NOT EDIT BY HAND — change the master list, then run:
//   node scripts/sync_creatures.mjs
import Foundation

/// On-device power data: the SAME master list the server's resolver uses, so a
/// result worked out on the phone (offline fallback, on-device narration)
/// always names the same winner as the cloud.
enum OnDeviceTiers {

    /// Creature id → power tier (1 = tiny bug, 10 = god).
    static let tier: [String: Int] = [
        "albatross": 2, "alpaca": 3, "ammit": 7, "ankylosaurus": 7,
        "apollo": 10, "ares": 10, "army_ant": 1, "artemis": 10,
        "athena": 10, "baku": 6, "bald_eagle": 4, "barn_owl": 2,
        "barracuda": 4, "basilisk": 8, "beagle": 2, "betta_fish": 1,
        "blue_ringed_octopus": 3, "boar": 4, "bombardier_beetle": 1, "border_collie": 3,
        "bull": 5, "bulldog": 3, "bullet_ant": 1, "canary": 1,
        "centipede": 1, "cerberus": 8, "cheetah": 4, "chicken": 2,
        "chihuahua": 2, "chimera": 8, "cobra": 3, "cockatiel": 1,
        "coelacanth": 3, "corgi": 2, "cow": 4, "crocodile": 7,
        "crow": 2, "dachshund": 2, "dire_wolf": 5, "dodo": 1,
        "donkey": 4, "dragon": 9, "dragonfly": 1, "duck": 2,
        "electric_eel": 4, "elephant": 8, "fire_ant": 1, "gerbil": 1,
        "german_shepherd": 4, "giant_squid": 7, "giraffe": 5, "goat": 3,
        "golden_retriever": 3, "goldfish": 1, "goose": 2, "gorilla": 6,
        "great_dane": 4, "great_white_shark": 8, "griffin": 7, "grizzly_bear": 7,
        "guinea_pig": 1, "hades": 10, "hammerhead_shark": 7, "hamster": 1,
        "harpy_eagle": 4, "hephaestus": 10, "hercules": 10, "hermes": 10,
        "hippopotamus": 7, "honey_badger": 3, "hornet": 1, "horse": 5,
        "husky": 3, "hydra": 9, "jackalope": 3, "kirin": 7,
        "kitsune": 6, "komodo_dragon": 5, "kraken": 9, "kronos": 10,
        "labrador": 3, "lamb": 2, "leopard_gecko": 1, "leviathan": 9,
        "lion": 6, "llama": 4, "maine_coon": 2, "manticore": 7,
        "mantis_shrimp": 2, "medusa": 10, "megalodon": 9, "minotaur": 6,
        "moose": 6, "mule": 4, "nue": 7, "octopus": 3,
        "orca": 9, "ox": 5, "parakeet": 1, "pelican": 2,
        "peregrine_falcon": 3, "persian_cat": 2, "peryton": 5, "pet_rabbit": 1,
        "phoenix": 8, "pig": 4, "piglet": 2, "piranha": 2,
        "poodle": 3, "poseidon": 10, "praying_mantis": 1, "pteranodon": 5,
        "pterodactyl": 3, "pug": 2, "ram": 3, "rhinoceros": 7,
        "roc": 8, "rooster": 2, "saber_tooth_tiger": 6, "scorpion": 2,
        "sheep": 3, "sphinx": 7, "spinosaurus": 8, "stag_beetle": 1,
        "swordfish": 5, "t_rex": 8, "tabby_cat": 2, "tarantula": 2,
        "therizinosaurus": 6, "thunderbird": 9, "tiger": 6, "triceratops": 7,
        "turkey": 2, "unicorn": 6, "velociraptor": 5, "wasp": 1,
        "werewolf": 6, "wolf": 4, "wolverine": 4, "woolly_mammoth": 7,
        "wyvern": 7, "zebra": 4, "zeus": 10,
    ]

    /// Fractional realism nudges within a tier (e.g. tiger edges lion). The
    /// effective power is `2^(tier + adjust)`.
    static let tierAdjust: [String: Double] = [
        "alpaca": 0.45, "apollo": 0.5, "ares": 0.45, "artemis": 0.4,
        "athena": 0.55, "beagle": 0.6, "betta_fish": 0.3, "border_collie": 0.1,
        "bull": 0.5, "bulldog": 0.2, "canary": 0.35, "chicken": -0.28,
        "chihuahua": 0.05, "cockatiel": 0.6, "corgi": 0.5, "cow": 0.8,
        "dachshund": 0.2, "donkey": 0.4, "duck": -0.35, "gerbil": 0.45,
        "german_shepherd": -0.3, "goat": 0.3, "golden_retriever": 0.35, "goldfish": 0.2,
        "goose": 0.35, "great_dane": -0.2, "guinea_pig": 0.7, "hades": 0.65,
        "hamster": 0.5, "hephaestus": 0.35, "hercules": 0.48, "hermes": 0.3,
        "horse": 0.2, "husky": 0.5, "kronos": 0.8, "labrador": 0.4,
        "lamb": 0.18, "leopard_gecko": 0.4, "llama": 0.2, "maine_coon": 0.45,
        "medusa": 0.1, "mule": 0.55, "ox": 0.4, "parakeet": 0.55,
        "persian_cat": 0.15, "pet_rabbit": 0.8, "pig": -0.35, "piglet": 0.1,
        "poodle": -0.05, "poseidon": 0.7, "pug": 0.3, "ram": 0.75,
        "rooster": -0.15, "sheep": -0.1, "tabby_cat": 0.25, "tiger": 0.45,
        "turkey": 0.28, "zeus": 0.9,
    ]

    /// Greek gods — beat any mortal creature.
    static let deities: Set<String> = ["apollo", "ares", "artemis", "athena", "hades", "hephaestus", "hercules", "hermes", "kronos", "medusa", "poseidon", "zeus"]

    /// Water creatures — stranded out of water (land and sky arenas).
    static let sea: Set<String> = ["barracuda", "betta_fish", "blue_ringed_octopus", "coelacanth", "electric_eel", "giant_squid", "goldfish", "great_white_shark", "hammerhead_shark", "kraken", "leviathan", "mantis_shrimp", "megalodon", "octopus", "orca", "piranha", "swordfish"]

    /// Flying creatures — can't breathe in the deep-ocean arena.
    static let air: Set<String> = ["albatross", "bald_eagle", "barn_owl", "canary", "cockatiel", "crow", "dragonfly", "duck", "goose", "harpy_eagle", "hornet", "parakeet", "pelican", "peregrine_falcon", "phoenix", "pteranodon", "pterodactyl", "roc", "thunderbird"]

    /// Land creatures with working wings — at home in the sky arena.
    static let fliers: Set<String> = ["dragon", "griffin", "manticore", "peryton", "sphinx", "wyvern"]

    /// Land/air creatures that also swim — half strength in the ocean arena.
    static let swimmers: Set<String> = ["crocodile", "duck", "goose", "hippopotamus", "spinosaurus"]

    /// True for the app's built-in creatures (custom creatures are not listed).
    static func isBuiltIn(_ id: String) -> Bool { tier[id] != nil }

    /// Integer tier for an id, defaulting to 4 (a mid creature) when unknown.
    static func tier(for id: String) -> Int { tier[id] ?? 4 }

    /// Effective fractional tier = integer tier + realism nudge.
    static func effectiveTier(for id: String) -> Double {
        Double(tier(for: id)) + (tierAdjust[id] ?? 0)
    }
}
