#!/usr/bin/env node
// Keeps the iPhone app's creature data in step with the master list.
//
//   node scripts/sync_creatures.mjs          regenerate ios/.../OnDeviceTiers.swift
//   node scripts/sync_creatures.mjs --check  exit 1 if anything is out of sync
//
// The master list is backend/src/data/creatures.json. This script also checks
// that the iOS roster (Data/Animals.swift) has exactly the same creatures with
// the same names, so a creature can't be added to one side only.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const masterPath = join(root, 'backend/src/data/creatures.json');
const rosterPath = join(root, 'ios/WhoWouldWin/Data/Animals.swift');
const tiersPath = join(root, 'ios/WhoWouldWin/Services/OnDeviceTiers.swift');
const check = process.argv.includes('--check');

const creatures = JSON.parse(readFileSync(masterPath, 'utf8'));
const problems = [];

// ── Roster check ────────────────────────────────────────────────────────────
const roster = new Map();
const rosterSource = readFileSync(rosterPath, 'utf8');
for (const m of rosterSource.matchAll(/Animal\(id:\s*"([a-z0-9_]+)",\s*name:\s*"([^"]+)"/g)) {
  roster.set(m[1], m[2]);
}
const master = new Map(creatures.map(c => [c.id, c.name]));
for (const [id, name] of master) {
  if (!roster.has(id)) problems.push(`"${id}" is in the master list but not in Animals.swift`);
  else if (roster.get(id) !== name) problems.push(`"${id}" is named "${roster.get(id)}" in Animals.swift but "${name}" in the master list`);
}
for (const id of roster.keys()) {
  if (!master.has(id)) problems.push(`"${id}" is in Animals.swift but not in the master list`);
}

// ── Generate OnDeviceTiers.swift ────────────────────────────────────────────
const byId = [...creatures].sort((a, b) => a.id.localeCompare(b.id));
const idSet = list => `[${list.map(c => `"${c.id}"`).join(', ')}]`;
const wrap = (entries, perLine) => {
  const lines = [];
  for (let i = 0; i < entries.length; i += perLine) {
    lines.push('        ' + entries.slice(i, i + perLine).join(', ') + ',');
  }
  return lines.join('\n');
};

const swift = `// GENERATED by scripts/sync_creatures.mjs from backend/src/data/creatures.json.
// DO NOT EDIT BY HAND — change the master list, then run:
//   node scripts/sync_creatures.mjs
import Foundation

/// On-device power data: the SAME master list the server's resolver uses, so a
/// result worked out on the phone (offline fallback, on-device narration)
/// always names the same winner as the cloud.
enum OnDeviceTiers {

    /// Creature id → power tier (1 = tiny bug, 10 = god).
    static let tier: [String: Int] = [
${wrap(byId.map(c => `"${c.id}": ${c.tier}`), 4)}
    ]

    /// Fractional realism nudges within a tier (e.g. tiger edges lion). The
    /// effective power is \`2^(tier + adjust)\`.
    static let tierAdjust: [String: Double] = [
${wrap(byId.filter(c => c.adjust !== undefined).map(c => `"${c.id}": ${c.adjust}`), 4)}
    ]

    /// Greek gods — beat any mortal creature.
    static let deities: Set<String> = ${idSet(byId.filter(c => c.habitat === 'deity'))}

    /// Water creatures — stranded out of water (land and sky arenas).
    static let sea: Set<String> = ${idSet(byId.filter(c => c.habitat === 'sea'))}

    /// Flying creatures — can't breathe in the deep-ocean arena.
    static let air: Set<String> = ${idSet(byId.filter(c => c.habitat === 'air'))}

    /// Land creatures with working wings — at home in the sky arena.
    static let fliers: Set<String> = ${idSet(byId.filter(c => c.flies))}

    /// Land/air creatures that also swim — half strength in the ocean arena.
    static let swimmers: Set<String> = ${idSet(byId.filter(c => c.swims))}

    /// True for the app's built-in creatures (custom creatures are not listed).
    static func isBuiltIn(_ id: String) -> Bool { tier[id] != nil }

    /// Integer tier for an id, defaulting to 4 (a mid creature) when unknown.
    static func tier(for id: String) -> Int { tier[id] ?? 4 }

    /// Effective fractional tier = integer tier + realism nudge.
    static func effectiveTier(for id: String) -> Double {
        Double(tier(for: id)) + (tierAdjust[id] ?? 0)
    }
}
`;

let current = '';
try { current = readFileSync(tiersPath, 'utf8'); } catch { /* first run */ }

if (check) {
  if (current !== swift) problems.push('OnDeviceTiers.swift is out of date — run: node scripts/sync_creatures.mjs');
  if (problems.length) {
    console.error(problems.map(p => `✗ ${p}`).join('\n'));
    process.exit(1);
  }
  console.log(`✓ ${creatures.length} creatures in sync (master list, Animals.swift, OnDeviceTiers.swift)`);
} else {
  if (problems.length) {
    console.error(problems.map(p => `✗ ${p}`).join('\n'));
    process.exit(1);
  }
  writeFileSync(tiersPath, swift);
  console.log(`Wrote ${tiersPath} (${creatures.length} creatures)`);
}
